library(ggplot2)
housing <- read.csv("dataSets/landdata-states.csv")
f1 <- ggplot(housing, aes(x=Date, y=Home.Value, color=State)) + geom_line()
f2 <- ggplot(subset(housing, State %in% list("HI")), aes(x=Date, y=Home.Value, color=State)) + geom_line()
#windows(xpos= 0, ypos = 0)
#plot(a)
v1 <- process(f1,f2)
f3 <-ggplot(subset(housing, State %in% v1), aes(x=Date, y=Home.Value, color=State)) + geom_line()
windows(xpos = -1, ypos = 0)
plot(c + facet_wrap(~State))